// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package script

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// AddTorrent wires the Source radio toggle on the Add Torrent page so
// that selecting "Magnet" or "Upload file" hides the inactive input
// pane. The form's data-source attribute is updated alongside, which
// preserves the selection during in-page interactions even though the
// server re-renders the page on validation errors.
func AddTorrent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script>\n\t\t(function() {\n\t\t\tconst form = document.getElementById('add-torrent-form');\n\t\t\tif (!form) return;\n\n\t\t\tfunction applySource(source) {\n\t\t\t\tform.dataset.source = source;\n\t\t\t\tfor (const pane of form.querySelectorAll('[data-source-pane]')) {\n\t\t\t\t\tpane.hidden = pane.dataset.sourcePane !== source;\n\t\t\t\t}\n\t\t\t}\n\n\t\t\tform.addEventListener('change', function(evt) {\n\t\t\t\tconst radio = evt.target.closest('input[type=radio][name=source]');\n\t\t\t\tif (!radio || !radio.checked) return;\n\t\t\t\tapplySource(radio.value);\n\t\t\t});\n\n\t\t\tconst checked = form.querySelector('input[type=radio][name=source]:checked');\n\t\t\tapplySource(checked ? checked.value : 'magnet');\n\t\t})();\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
