// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package script

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// ConfirmPause replaces the default htmx:confirm behaviour with a version
// that pauses polling while the confirmation dialog is up. Native confirm()
// blocks the JS thread, so any "every Ns" poll timer that ticks during the
// dialog queues — and on dismissal it would race the user's click, often
// swapping the DOM out from under the request before it can fire. Adding the
// `htmx-confirming` class lets the table's hx-trigger filter skip the queued
// ticks; a 0ms timeout keeps the class set long enough for the catch-up
// ticks to drain after the dialog closes.
func ConfirmPause() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script>\n\t\tdocument.body.addEventListener('htmx:confirm', function(evt) {\n\t\t\tif (!evt.detail.question) return;\n\t\t\tevt.preventDefault();\n\t\t\tdocument.body.classList.add('htmx-confirming');\n\t\t\ttry {\n\t\t\t\tif (confirm(evt.detail.question)) {\n\t\t\t\t\tevt.detail.issueRequest(true);\n\t\t\t\t}\n\t\t\t} finally {\n\t\t\t\tsetTimeout(function() {\n\t\t\t\t\tdocument.body.classList.remove('htmx-confirming');\n\t\t\t\t}, 0);\n\t\t\t}\n\t\t});\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
