// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package script

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// DeleteDetail wires the torrent-detail page's Delete button to the
// shared delete dialog. On confirm it sends the DELETE request with
// the right ?files= flag and navigates back to the list on success.
// Uses document-level event delegation because ShowDetail is the
// HTMX poll target and the button is re-rendered every second.
func DeleteDetail() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script>\n\t\t(function() {\n\t\t\tdocument.addEventListener('click', function(evt) {\n\t\t\t\tconst button = evt.target.closest('#detail-delete-button');\n\t\t\t\tif (!button) return;\n\n\t\t\t\tconst hash = button.dataset.infoHash;\n\t\t\t\tconst complete = button.dataset.complete === 'true';\n\t\t\t\twindow.openDeleteDialog({ hashes: [hash], anyComplete: complete }, function(deleteFiles) {\n\t\t\t\t\tbutton.classList.add('htmx-request');\n\t\t\t\t\tfetch('/ui/torrents/' + hash + '?files=' + deleteFiles, { method: 'DELETE' }).then(function(resp) {\n\t\t\t\t\t\tbutton.classList.remove('htmx-request');\n\t\t\t\t\t\tif (resp.ok) {\n\t\t\t\t\t\t\twindow.location = '/';\n\t\t\t\t\t\t}\n\t\t\t\t\t});\n\t\t\t\t});\n\t\t\t});\n\t\t})();\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
