// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package torrent_test

import (
	"context"

	"github.com/anacrolix/chansync/events"
	torrent0 "github.com/anacrolix/torrent"
	"github.com/anacrolix/torrent/metainfo"
	"github.com/dsb-labs/torrents/internal/server/torrent"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// AddMagnet provides a mock function for the type MockClient
func (_mock *MockClient) AddMagnet(uri string) (torrent.Torrent, error) {
	ret := _mock.Called(uri)

	if len(ret) == 0 {
		panic("no return value specified for AddMagnet")
	}

	var r0 torrent.Torrent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (torrent.Torrent, error)); ok {
		return returnFunc(uri)
	}
	if returnFunc, ok := ret.Get(0).(func(string) torrent.Torrent); ok {
		r0 = returnFunc(uri)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(torrent.Torrent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(uri)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_AddMagnet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMagnet'
type MockClient_AddMagnet_Call struct {
	*mock.Call
}

// AddMagnet is a helper method to define mock.On call
//   - uri string
func (_e *MockClient_Expecter) AddMagnet(uri interface{}) *MockClient_AddMagnet_Call {
	return &MockClient_AddMagnet_Call{Call: _e.mock.On("AddMagnet", uri)}
}

func (_c *MockClient_AddMagnet_Call) Run(run func(uri string)) *MockClient_AddMagnet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_AddMagnet_Call) Return(torrent1 torrent.Torrent, err error) *MockClient_AddMagnet_Call {
	_c.Call.Return(torrent1, err)
	return _c
}

func (_c *MockClient_AddMagnet_Call) RunAndReturn(run func(uri string) (torrent.Torrent, error)) *MockClient_AddMagnet_Call {
	_c.Call.Return(run)
	return _c
}

// AddTorrent provides a mock function for the type MockClient
func (_mock *MockClient) AddTorrent(mi *metainfo.MetaInfo) (torrent.Torrent, error) {
	ret := _mock.Called(mi)

	if len(ret) == 0 {
		panic("no return value specified for AddTorrent")
	}

	var r0 torrent.Torrent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*metainfo.MetaInfo) (torrent.Torrent, error)); ok {
		return returnFunc(mi)
	}
	if returnFunc, ok := ret.Get(0).(func(*metainfo.MetaInfo) torrent.Torrent); ok {
		r0 = returnFunc(mi)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(torrent.Torrent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*metainfo.MetaInfo) error); ok {
		r1 = returnFunc(mi)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_AddTorrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTorrent'
type MockClient_AddTorrent_Call struct {
	*mock.Call
}

// AddTorrent is a helper method to define mock.On call
//   - mi *metainfo.MetaInfo
func (_e *MockClient_Expecter) AddTorrent(mi interface{}) *MockClient_AddTorrent_Call {
	return &MockClient_AddTorrent_Call{Call: _e.mock.On("AddTorrent", mi)}
}

func (_c *MockClient_AddTorrent_Call) Run(run func(mi *metainfo.MetaInfo)) *MockClient_AddTorrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *metainfo.MetaInfo
		if args[0] != nil {
			arg0 = args[0].(*metainfo.MetaInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_AddTorrent_Call) Return(torrent1 torrent.Torrent, err error) *MockClient_AddTorrent_Call {
	_c.Call.Return(torrent1, err)
	return _c
}

func (_c *MockClient_AddTorrent_Call) RunAndReturn(run func(mi *metainfo.MetaInfo) (torrent.Torrent, error)) *MockClient_AddTorrent_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockClient
func (_mock *MockClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(err error) *MockClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Torrent provides a mock function for the type MockClient
func (_mock *MockClient) Torrent(hash metainfo.Hash) (torrent.Torrent, bool) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for Torrent")
	}

	var r0 torrent.Torrent
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(metainfo.Hash) (torrent.Torrent, bool)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(metainfo.Hash) torrent.Torrent); ok {
		r0 = returnFunc(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(torrent.Torrent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(metainfo.Hash) bool); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockClient_Torrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Torrent'
type MockClient_Torrent_Call struct {
	*mock.Call
}

// Torrent is a helper method to define mock.On call
//   - hash metainfo.Hash
func (_e *MockClient_Expecter) Torrent(hash interface{}) *MockClient_Torrent_Call {
	return &MockClient_Torrent_Call{Call: _e.mock.On("Torrent", hash)}
}

func (_c *MockClient_Torrent_Call) Run(run func(hash metainfo.Hash)) *MockClient_Torrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metainfo.Hash
		if args[0] != nil {
			arg0 = args[0].(metainfo.Hash)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_Torrent_Call) Return(torrent1 torrent.Torrent, b bool) *MockClient_Torrent_Call {
	_c.Call.Return(torrent1, b)
	return _c
}

func (_c *MockClient_Torrent_Call) RunAndReturn(run func(hash metainfo.Hash) (torrent.Torrent, bool)) *MockClient_Torrent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTorrent creates a new instance of MockTorrent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTorrent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTorrent {
	mock := &MockTorrent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTorrent is an autogenerated mock type for the Torrent type
type MockTorrent struct {
	mock.Mock
}

type MockTorrent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTorrent) EXPECT() *MockTorrent_Expecter {
	return &MockTorrent_Expecter{mock: &_m.Mock}
}

// BytesCompleted provides a mock function for the type MockTorrent
func (_mock *MockTorrent) BytesCompleted() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BytesCompleted")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockTorrent_BytesCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BytesCompleted'
type MockTorrent_BytesCompleted_Call struct {
	*mock.Call
}

// BytesCompleted is a helper method to define mock.On call
func (_e *MockTorrent_Expecter) BytesCompleted() *MockTorrent_BytesCompleted_Call {
	return &MockTorrent_BytesCompleted_Call{Call: _e.mock.On("BytesCompleted")}
}

func (_c *MockTorrent_BytesCompleted_Call) Run(run func()) *MockTorrent_BytesCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTorrent_BytesCompleted_Call) Return(n int64) *MockTorrent_BytesCompleted_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockTorrent_BytesCompleted_Call) RunAndReturn(run func() int64) *MockTorrent_BytesCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadAll provides a mock function for the type MockTorrent
func (_mock *MockTorrent) DownloadAll() {
	_mock.Called()
	return
}

// MockTorrent_DownloadAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadAll'
type MockTorrent_DownloadAll_Call struct {
	*mock.Call
}

// DownloadAll is a helper method to define mock.On call
func (_e *MockTorrent_Expecter) DownloadAll() *MockTorrent_DownloadAll_Call {
	return &MockTorrent_DownloadAll_Call{Call: _e.mock.On("DownloadAll")}
}

func (_c *MockTorrent_DownloadAll_Call) Run(run func()) *MockTorrent_DownloadAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTorrent_DownloadAll_Call) Return() *MockTorrent_DownloadAll_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTorrent_DownloadAll_Call) RunAndReturn(run func()) *MockTorrent_DownloadAll_Call {
	_c.Run(run)
	return _c
}

// Drop provides a mock function for the type MockTorrent
func (_mock *MockTorrent) Drop() {
	_mock.Called()
	return
}

// MockTorrent_Drop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Drop'
type MockTorrent_Drop_Call struct {
	*mock.Call
}

// Drop is a helper method to define mock.On call
func (_e *MockTorrent_Expecter) Drop() *MockTorrent_Drop_Call {
	return &MockTorrent_Drop_Call{Call: _e.mock.On("Drop")}
}

func (_c *MockTorrent_Drop_Call) Run(run func()) *MockTorrent_Drop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTorrent_Drop_Call) Return() *MockTorrent_Drop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTorrent_Drop_Call) RunAndReturn(run func()) *MockTorrent_Drop_Call {
	_c.Run(run)
	return _c
}

// GotInfo provides a mock function for the type MockTorrent
func (_mock *MockTorrent) GotInfo() events.Done {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GotInfo")
	}

	var r0 events.Done
	if returnFunc, ok := ret.Get(0).(func() events.Done); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(events.Done)
		}
	}
	return r0
}

// MockTorrent_GotInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GotInfo'
type MockTorrent_GotInfo_Call struct {
	*mock.Call
}

// GotInfo is a helper method to define mock.On call
func (_e *MockTorrent_Expecter) GotInfo() *MockTorrent_GotInfo_Call {
	return &MockTorrent_GotInfo_Call{Call: _e.mock.On("GotInfo")}
}

func (_c *MockTorrent_GotInfo_Call) Run(run func()) *MockTorrent_GotInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTorrent_GotInfo_Call) Return(done events.Done) *MockTorrent_GotInfo_Call {
	_c.Call.Return(done)
	return _c
}

func (_c *MockTorrent_GotInfo_Call) RunAndReturn(run func() events.Done) *MockTorrent_GotInfo_Call {
	_c.Call.Return(run)
	return _c
}

// InfoHash provides a mock function for the type MockTorrent
func (_mock *MockTorrent) InfoHash() metainfo.Hash {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InfoHash")
	}

	var r0 metainfo.Hash
	if returnFunc, ok := ret.Get(0).(func() metainfo.Hash); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metainfo.Hash)
		}
	}
	return r0
}

// MockTorrent_InfoHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InfoHash'
type MockTorrent_InfoHash_Call struct {
	*mock.Call
}

// InfoHash is a helper method to define mock.On call
func (_e *MockTorrent_Expecter) InfoHash() *MockTorrent_InfoHash_Call {
	return &MockTorrent_InfoHash_Call{Call: _e.mock.On("InfoHash")}
}

func (_c *MockTorrent_InfoHash_Call) Run(run func()) *MockTorrent_InfoHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTorrent_InfoHash_Call) Return(v metainfo.Hash) *MockTorrent_InfoHash_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockTorrent_InfoHash_Call) RunAndReturn(run func() metainfo.Hash) *MockTorrent_InfoHash_Call {
	_c.Call.Return(run)
	return _c
}

// Length provides a mock function for the type MockTorrent
func (_mock *MockTorrent) Length() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Length")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockTorrent_Length_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Length'
type MockTorrent_Length_Call struct {
	*mock.Call
}

// Length is a helper method to define mock.On call
func (_e *MockTorrent_Expecter) Length() *MockTorrent_Length_Call {
	return &MockTorrent_Length_Call{Call: _e.mock.On("Length")}
}

func (_c *MockTorrent_Length_Call) Run(run func()) *MockTorrent_Length_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTorrent_Length_Call) Return(n int64) *MockTorrent_Length_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockTorrent_Length_Call) RunAndReturn(run func() int64) *MockTorrent_Length_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockTorrent
func (_mock *MockTorrent) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTorrent_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockTorrent_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockTorrent_Expecter) Name() *MockTorrent_Name_Call {
	return &MockTorrent_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockTorrent_Name_Call) Run(run func()) *MockTorrent_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTorrent_Name_Call) Return(s string) *MockTorrent_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTorrent_Name_Call) RunAndReturn(run func() string) *MockTorrent_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function for the type MockTorrent
func (_mock *MockTorrent) Stats() torrent0.TorrentStats {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 torrent0.TorrentStats
	if returnFunc, ok := ret.Get(0).(func() torrent0.TorrentStats); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(torrent0.TorrentStats)
	}
	return r0
}

// MockTorrent_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockTorrent_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockTorrent_Expecter) Stats() *MockTorrent_Stats_Call {
	return &MockTorrent_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockTorrent_Stats_Call) Run(run func()) *MockTorrent_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTorrent_Stats_Call) Return(torrentStats torrent0.TorrentStats) *MockTorrent_Stats_Call {
	_c.Call.Return(torrentStats)
	return _c
}

func (_c *MockTorrent_Stats_Call) RunAndReturn(run func() torrent0.TorrentStats) *MockTorrent_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyDataContext provides a mock function for the type MockTorrent
func (_mock *MockTorrent) VerifyDataContext(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for VerifyDataContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTorrent_VerifyDataContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyDataContext'
type MockTorrent_VerifyDataContext_Call struct {
	*mock.Call
}

// VerifyDataContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTorrent_Expecter) VerifyDataContext(ctx interface{}) *MockTorrent_VerifyDataContext_Call {
	return &MockTorrent_VerifyDataContext_Call{Call: _e.mock.On("VerifyDataContext", ctx)}
}

func (_c *MockTorrent_VerifyDataContext_Call) Run(run func(ctx context.Context)) *MockTorrent_VerifyDataContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTorrent_VerifyDataContext_Call) Return(err error) *MockTorrent_VerifyDataContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTorrent_VerifyDataContext_Call) RunAndReturn(run func(ctx context.Context) error) *MockTorrent_VerifyDataContext_Call {
	_c.Call.Return(run)
	return _c
}
