// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service_test

import (
	"context"
	"io"

	"github.com/dsb-labs/torrents/internal/server/database"
	"github.com/dsb-labs/torrents/internal/server/torrent"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTorrentEngine creates a new instance of MockTorrentEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTorrentEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTorrentEngine {
	mock := &MockTorrentEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTorrentEngine is an autogenerated mock type for the TorrentEngine type
type MockTorrentEngine struct {
	mock.Mock
}

type MockTorrentEngine_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTorrentEngine) EXPECT() *MockTorrentEngine_Expecter {
	return &MockTorrentEngine_Expecter{mock: &_m.Mock}
}

// AddFile provides a mock function for the type MockTorrentEngine
func (_mock *MockTorrentEngine) AddFile(ctx context.Context, r io.Reader) (torrent.InfoHash, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for AddFile")
	}

	var r0 torrent.InfoHash
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader) (torrent.InfoHash, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader) torrent.InfoHash); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Get(0).(torrent.InfoHash)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTorrentEngine_AddFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFile'
type MockTorrentEngine_AddFile_Call struct {
	*mock.Call
}

// AddFile is a helper method to define mock.On call
//   - ctx context.Context
//   - r io.Reader
func (_e *MockTorrentEngine_Expecter) AddFile(ctx interface{}, r interface{}) *MockTorrentEngine_AddFile_Call {
	return &MockTorrentEngine_AddFile_Call{Call: _e.mock.On("AddFile", ctx, r)}
}

func (_c *MockTorrentEngine_AddFile_Call) Run(run func(ctx context.Context, r io.Reader)) *MockTorrentEngine_AddFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTorrentEngine_AddFile_Call) Return(infoHash torrent.InfoHash, err error) *MockTorrentEngine_AddFile_Call {
	_c.Call.Return(infoHash, err)
	return _c
}

func (_c *MockTorrentEngine_AddFile_Call) RunAndReturn(run func(ctx context.Context, r io.Reader) (torrent.InfoHash, error)) *MockTorrentEngine_AddFile_Call {
	_c.Call.Return(run)
	return _c
}

// AddMagnet provides a mock function for the type MockTorrentEngine
func (_mock *MockTorrentEngine) AddMagnet(ctx context.Context, uri string) (torrent.InfoHash, error) {
	ret := _mock.Called(ctx, uri)

	if len(ret) == 0 {
		panic("no return value specified for AddMagnet")
	}

	var r0 torrent.InfoHash
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (torrent.InfoHash, error)); ok {
		return returnFunc(ctx, uri)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) torrent.InfoHash); ok {
		r0 = returnFunc(ctx, uri)
	} else {
		r0 = ret.Get(0).(torrent.InfoHash)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uri)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTorrentEngine_AddMagnet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMagnet'
type MockTorrentEngine_AddMagnet_Call struct {
	*mock.Call
}

// AddMagnet is a helper method to define mock.On call
//   - ctx context.Context
//   - uri string
func (_e *MockTorrentEngine_Expecter) AddMagnet(ctx interface{}, uri interface{}) *MockTorrentEngine_AddMagnet_Call {
	return &MockTorrentEngine_AddMagnet_Call{Call: _e.mock.On("AddMagnet", ctx, uri)}
}

func (_c *MockTorrentEngine_AddMagnet_Call) Run(run func(ctx context.Context, uri string)) *MockTorrentEngine_AddMagnet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTorrentEngine_AddMagnet_Call) Return(infoHash torrent.InfoHash, err error) *MockTorrentEngine_AddMagnet_Call {
	_c.Call.Return(infoHash, err)
	return _c
}

func (_c *MockTorrentEngine_AddMagnet_Call) RunAndReturn(run func(ctx context.Context, uri string) (torrent.InfoHash, error)) *MockTorrentEngine_AddMagnet_Call {
	_c.Call.Return(run)
	return _c
}

// Pause provides a mock function for the type MockTorrentEngine
func (_mock *MockTorrentEngine) Pause(ctx context.Context, hash torrent.InfoHash) error {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for Pause")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, torrent.InfoHash) error); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTorrentEngine_Pause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pause'
type MockTorrentEngine_Pause_Call struct {
	*mock.Call
}

// Pause is a helper method to define mock.On call
//   - ctx context.Context
//   - hash torrent.InfoHash
func (_e *MockTorrentEngine_Expecter) Pause(ctx interface{}, hash interface{}) *MockTorrentEngine_Pause_Call {
	return &MockTorrentEngine_Pause_Call{Call: _e.mock.On("Pause", ctx, hash)}
}

func (_c *MockTorrentEngine_Pause_Call) Run(run func(ctx context.Context, hash torrent.InfoHash)) *MockTorrentEngine_Pause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 torrent.InfoHash
		if args[1] != nil {
			arg1 = args[1].(torrent.InfoHash)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTorrentEngine_Pause_Call) Return(err error) *MockTorrentEngine_Pause_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTorrentEngine_Pause_Call) RunAndReturn(run func(ctx context.Context, hash torrent.InfoHash) error) *MockTorrentEngine_Pause_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockTorrentEngine
func (_mock *MockTorrentEngine) Remove(ctx context.Context, hash torrent.InfoHash) error {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, torrent.InfoHash) error); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTorrentEngine_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockTorrentEngine_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - hash torrent.InfoHash
func (_e *MockTorrentEngine_Expecter) Remove(ctx interface{}, hash interface{}) *MockTorrentEngine_Remove_Call {
	return &MockTorrentEngine_Remove_Call{Call: _e.mock.On("Remove", ctx, hash)}
}

func (_c *MockTorrentEngine_Remove_Call) Run(run func(ctx context.Context, hash torrent.InfoHash)) *MockTorrentEngine_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 torrent.InfoHash
		if args[1] != nil {
			arg1 = args[1].(torrent.InfoHash)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTorrentEngine_Remove_Call) Return(err error) *MockTorrentEngine_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTorrentEngine_Remove_Call) RunAndReturn(run func(ctx context.Context, hash torrent.InfoHash) error) *MockTorrentEngine_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Resume provides a mock function for the type MockTorrentEngine
func (_mock *MockTorrentEngine) Resume(ctx context.Context, hash torrent.InfoHash) error {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, torrent.InfoHash) error); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTorrentEngine_Resume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resume'
type MockTorrentEngine_Resume_Call struct {
	*mock.Call
}

// Resume is a helper method to define mock.On call
//   - ctx context.Context
//   - hash torrent.InfoHash
func (_e *MockTorrentEngine_Expecter) Resume(ctx interface{}, hash interface{}) *MockTorrentEngine_Resume_Call {
	return &MockTorrentEngine_Resume_Call{Call: _e.mock.On("Resume", ctx, hash)}
}

func (_c *MockTorrentEngine_Resume_Call) Run(run func(ctx context.Context, hash torrent.InfoHash)) *MockTorrentEngine_Resume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 torrent.InfoHash
		if args[1] != nil {
			arg1 = args[1].(torrent.InfoHash)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTorrentEngine_Resume_Call) Return(err error) *MockTorrentEngine_Resume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTorrentEngine_Resume_Call) RunAndReturn(run func(ctx context.Context, hash torrent.InfoHash) error) *MockTorrentEngine_Resume_Call {
	_c.Call.Return(run)
	return _c
}

// Snapshot provides a mock function for the type MockTorrentEngine
func (_mock *MockTorrentEngine) Snapshot(hash torrent.InfoHash) (torrent.Progress, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 torrent.Progress
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(torrent.InfoHash) (torrent.Progress, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(torrent.InfoHash) torrent.Progress); ok {
		r0 = returnFunc(hash)
	} else {
		r0 = ret.Get(0).(torrent.Progress)
	}
	if returnFunc, ok := ret.Get(1).(func(torrent.InfoHash) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTorrentEngine_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type MockTorrentEngine_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
//   - hash torrent.InfoHash
func (_e *MockTorrentEngine_Expecter) Snapshot(hash interface{}) *MockTorrentEngine_Snapshot_Call {
	return &MockTorrentEngine_Snapshot_Call{Call: _e.mock.On("Snapshot", hash)}
}

func (_c *MockTorrentEngine_Snapshot_Call) Run(run func(hash torrent.InfoHash)) *MockTorrentEngine_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 torrent.InfoHash
		if args[0] != nil {
			arg0 = args[0].(torrent.InfoHash)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTorrentEngine_Snapshot_Call) Return(progress torrent.Progress, err error) *MockTorrentEngine_Snapshot_Call {
	_c.Call.Return(progress, err)
	return _c
}

func (_c *MockTorrentEngine_Snapshot_Call) RunAndReturn(run func(hash torrent.InfoHash) (torrent.Progress, error)) *MockTorrentEngine_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTorrentRepository creates a new instance of MockTorrentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTorrentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTorrentRepository {
	mock := &MockTorrentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTorrentRepository is an autogenerated mock type for the TorrentRepository type
type MockTorrentRepository struct {
	mock.Mock
}

type MockTorrentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTorrentRepository) EXPECT() *MockTorrentRepository_Expecter {
	return &MockTorrentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTorrentRepository
func (_mock *MockTorrentRepository) Create(ctx context.Context, t database.Torrent) error {
	ret := _mock.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.Torrent) error); ok {
		r0 = returnFunc(ctx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTorrentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTorrentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t database.Torrent
func (_e *MockTorrentRepository_Expecter) Create(ctx interface{}, t interface{}) *MockTorrentRepository_Create_Call {
	return &MockTorrentRepository_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *MockTorrentRepository_Create_Call) Run(run func(ctx context.Context, t database.Torrent)) *MockTorrentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.Torrent
		if args[1] != nil {
			arg1 = args[1].(database.Torrent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTorrentRepository_Create_Call) Return(err error) *MockTorrentRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTorrentRepository_Create_Call) RunAndReturn(run func(ctx context.Context, t database.Torrent) error) *MockTorrentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTorrentRepository
func (_mock *MockTorrentRepository) Delete(ctx context.Context, infoHash string) error {
	ret := _mock.Called(ctx, infoHash)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, infoHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTorrentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTorrentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - infoHash string
func (_e *MockTorrentRepository_Expecter) Delete(ctx interface{}, infoHash interface{}) *MockTorrentRepository_Delete_Call {
	return &MockTorrentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, infoHash)}
}

func (_c *MockTorrentRepository_Delete_Call) Run(run func(ctx context.Context, infoHash string)) *MockTorrentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTorrentRepository_Delete_Call) Return(err error) *MockTorrentRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTorrentRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, infoHash string) error) *MockTorrentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockTorrentRepository
func (_mock *MockTorrentRepository) Get(ctx context.Context, infoHash string) (database.Torrent, error) {
	ret := _mock.Called(ctx, infoHash)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 database.Torrent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (database.Torrent, error)); ok {
		return returnFunc(ctx, infoHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) database.Torrent); ok {
		r0 = returnFunc(ctx, infoHash)
	} else {
		r0 = ret.Get(0).(database.Torrent)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, infoHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTorrentRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTorrentRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - infoHash string
func (_e *MockTorrentRepository_Expecter) Get(ctx interface{}, infoHash interface{}) *MockTorrentRepository_Get_Call {
	return &MockTorrentRepository_Get_Call{Call: _e.mock.On("Get", ctx, infoHash)}
}

func (_c *MockTorrentRepository_Get_Call) Run(run func(ctx context.Context, infoHash string)) *MockTorrentRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTorrentRepository_Get_Call) Return(torrent1 database.Torrent, err error) *MockTorrentRepository_Get_Call {
	_c.Call.Return(torrent1, err)
	return _c
}

func (_c *MockTorrentRepository_Get_Call) RunAndReturn(run func(ctx context.Context, infoHash string) (database.Torrent, error)) *MockTorrentRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTorrentRepository
func (_mock *MockTorrentRepository) List(ctx context.Context) ([]database.Torrent, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []database.Torrent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]database.Torrent, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []database.Torrent); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Torrent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTorrentRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTorrentRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTorrentRepository_Expecter) List(ctx interface{}) *MockTorrentRepository_List_Call {
	return &MockTorrentRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockTorrentRepository_List_Call) Run(run func(ctx context.Context)) *MockTorrentRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTorrentRepository_List_Call) Return(torrents []database.Torrent, err error) *MockTorrentRepository_List_Call {
	_c.Call.Return(torrents, err)
	return _c
}

func (_c *MockTorrentRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]database.Torrent, error)) *MockTorrentRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SetPaused provides a mock function for the type MockTorrentRepository
func (_mock *MockTorrentRepository) SetPaused(ctx context.Context, infoHash string, paused bool) error {
	ret := _mock.Called(ctx, infoHash, paused)

	if len(ret) == 0 {
		panic("no return value specified for SetPaused")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, infoHash, paused)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTorrentRepository_SetPaused_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPaused'
type MockTorrentRepository_SetPaused_Call struct {
	*mock.Call
}

// SetPaused is a helper method to define mock.On call
//   - ctx context.Context
//   - infoHash string
//   - paused bool
func (_e *MockTorrentRepository_Expecter) SetPaused(ctx interface{}, infoHash interface{}, paused interface{}) *MockTorrentRepository_SetPaused_Call {
	return &MockTorrentRepository_SetPaused_Call{Call: _e.mock.On("SetPaused", ctx, infoHash, paused)}
}

func (_c *MockTorrentRepository_SetPaused_Call) Run(run func(ctx context.Context, infoHash string, paused bool)) *MockTorrentRepository_SetPaused_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTorrentRepository_SetPaused_Call) Return(err error) *MockTorrentRepository_SetPaused_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTorrentRepository_SetPaused_Call) RunAndReturn(run func(ctx context.Context, infoHash string, paused bool) error) *MockTorrentRepository_SetPaused_Call {
	_c.Call.Return(run)
	return _c
}
