ALTER TABLE torrent ADD COLUMN name TEXT NOT NULL DEFAULT '';
ALTER TABLE torrent ADD COLUMN length INTEGER NOT NULL DEFAULT 0;
ALTER TABLE torrent ADD COLUMN bytes_completed INTEGER NOT NULL DEFAULT 0;
