// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api_test

import (
	"context"

	"github.com/dsb-labs/torrents/internal/server/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockValidatable creates a new instance of MockValidatable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidatable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidatable {
	mock := &MockValidatable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValidatable is an autogenerated mock type for the Validatable type
type MockValidatable struct {
	mock.Mock
}

type MockValidatable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidatable) EXPECT() *MockValidatable_Expecter {
	return &MockValidatable_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type MockValidatable
func (_mock *MockValidatable) Validate() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockValidatable_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockValidatable_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
func (_e *MockValidatable_Expecter) Validate() *MockValidatable_Validate_Call {
	return &MockValidatable_Validate_Call{Call: _e.mock.On("Validate")}
}

func (_c *MockValidatable_Validate_Call) Run(run func()) *MockValidatable_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValidatable_Validate_Call) Return(err error) *MockValidatable_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockValidatable_Validate_Call) RunAndReturn(run func() error) *MockValidatable_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTorrentService creates a new instance of MockTorrentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTorrentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTorrentService {
	mock := &MockTorrentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTorrentService is an autogenerated mock type for the TorrentService type
type MockTorrentService struct {
	mock.Mock
}

type MockTorrentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTorrentService) EXPECT() *MockTorrentService_Expecter {
	return &MockTorrentService_Expecter{mock: &_m.Mock}
}

// AddMagnet provides a mock function for the type MockTorrentService
func (_mock *MockTorrentService) AddMagnet(ctx context.Context, uri string, opts service.AddOptions) (service.Torrent, error) {
	ret := _mock.Called(ctx, uri, opts)

	if len(ret) == 0 {
		panic("no return value specified for AddMagnet")
	}

	var r0 service.Torrent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, service.AddOptions) (service.Torrent, error)); ok {
		return returnFunc(ctx, uri, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, service.AddOptions) service.Torrent); ok {
		r0 = returnFunc(ctx, uri, opts)
	} else {
		r0 = ret.Get(0).(service.Torrent)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, service.AddOptions) error); ok {
		r1 = returnFunc(ctx, uri, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTorrentService_AddMagnet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMagnet'
type MockTorrentService_AddMagnet_Call struct {
	*mock.Call
}

// AddMagnet is a helper method to define mock.On call
//   - ctx context.Context
//   - uri string
//   - opts service.AddOptions
func (_e *MockTorrentService_Expecter) AddMagnet(ctx interface{}, uri interface{}, opts interface{}) *MockTorrentService_AddMagnet_Call {
	return &MockTorrentService_AddMagnet_Call{Call: _e.mock.On("AddMagnet", ctx, uri, opts)}
}

func (_c *MockTorrentService_AddMagnet_Call) Run(run func(ctx context.Context, uri string, opts service.AddOptions)) *MockTorrentService_AddMagnet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 service.AddOptions
		if args[2] != nil {
			arg2 = args[2].(service.AddOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTorrentService_AddMagnet_Call) Return(torrent service.Torrent, err error) *MockTorrentService_AddMagnet_Call {
	_c.Call.Return(torrent, err)
	return _c
}

func (_c *MockTorrentService_AddMagnet_Call) RunAndReturn(run func(ctx context.Context, uri string, opts service.AddOptions) (service.Torrent, error)) *MockTorrentService_AddMagnet_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockTorrentService
func (_mock *MockTorrentService) Get(ctx context.Context, infoHash string) (service.Torrent, error) {
	ret := _mock.Called(ctx, infoHash)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 service.Torrent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (service.Torrent, error)); ok {
		return returnFunc(ctx, infoHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) service.Torrent); ok {
		r0 = returnFunc(ctx, infoHash)
	} else {
		r0 = ret.Get(0).(service.Torrent)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, infoHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTorrentService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTorrentService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - infoHash string
func (_e *MockTorrentService_Expecter) Get(ctx interface{}, infoHash interface{}) *MockTorrentService_Get_Call {
	return &MockTorrentService_Get_Call{Call: _e.mock.On("Get", ctx, infoHash)}
}

func (_c *MockTorrentService_Get_Call) Run(run func(ctx context.Context, infoHash string)) *MockTorrentService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTorrentService_Get_Call) Return(torrent service.Torrent, err error) *MockTorrentService_Get_Call {
	_c.Call.Return(torrent, err)
	return _c
}

func (_c *MockTorrentService_Get_Call) RunAndReturn(run func(ctx context.Context, infoHash string) (service.Torrent, error)) *MockTorrentService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTorrentService
func (_mock *MockTorrentService) List(ctx context.Context) ([]service.Torrent, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []service.Torrent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]service.Torrent, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []service.Torrent); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Torrent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTorrentService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTorrentService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTorrentService_Expecter) List(ctx interface{}) *MockTorrentService_List_Call {
	return &MockTorrentService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockTorrentService_List_Call) Run(run func(ctx context.Context)) *MockTorrentService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTorrentService_List_Call) Return(torrents []service.Torrent, err error) *MockTorrentService_List_Call {
	_c.Call.Return(torrents, err)
	return _c
}

func (_c *MockTorrentService_List_Call) RunAndReturn(run func(ctx context.Context) ([]service.Torrent, error)) *MockTorrentService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Pause provides a mock function for the type MockTorrentService
func (_mock *MockTorrentService) Pause(ctx context.Context, infoHash string) error {
	ret := _mock.Called(ctx, infoHash)

	if len(ret) == 0 {
		panic("no return value specified for Pause")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, infoHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTorrentService_Pause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pause'
type MockTorrentService_Pause_Call struct {
	*mock.Call
}

// Pause is a helper method to define mock.On call
//   - ctx context.Context
//   - infoHash string
func (_e *MockTorrentService_Expecter) Pause(ctx interface{}, infoHash interface{}) *MockTorrentService_Pause_Call {
	return &MockTorrentService_Pause_Call{Call: _e.mock.On("Pause", ctx, infoHash)}
}

func (_c *MockTorrentService_Pause_Call) Run(run func(ctx context.Context, infoHash string)) *MockTorrentService_Pause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTorrentService_Pause_Call) Return(err error) *MockTorrentService_Pause_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTorrentService_Pause_Call) RunAndReturn(run func(ctx context.Context, infoHash string) error) *MockTorrentService_Pause_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockTorrentService
func (_mock *MockTorrentService) Remove(ctx context.Context, infoHash string) error {
	ret := _mock.Called(ctx, infoHash)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, infoHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTorrentService_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockTorrentService_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - infoHash string
func (_e *MockTorrentService_Expecter) Remove(ctx interface{}, infoHash interface{}) *MockTorrentService_Remove_Call {
	return &MockTorrentService_Remove_Call{Call: _e.mock.On("Remove", ctx, infoHash)}
}

func (_c *MockTorrentService_Remove_Call) Run(run func(ctx context.Context, infoHash string)) *MockTorrentService_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTorrentService_Remove_Call) Return(err error) *MockTorrentService_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTorrentService_Remove_Call) RunAndReturn(run func(ctx context.Context, infoHash string) error) *MockTorrentService_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Resume provides a mock function for the type MockTorrentService
func (_mock *MockTorrentService) Resume(ctx context.Context, infoHash string) error {
	ret := _mock.Called(ctx, infoHash)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, infoHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTorrentService_Resume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resume'
type MockTorrentService_Resume_Call struct {
	*mock.Call
}

// Resume is a helper method to define mock.On call
//   - ctx context.Context
//   - infoHash string
func (_e *MockTorrentService_Expecter) Resume(ctx interface{}, infoHash interface{}) *MockTorrentService_Resume_Call {
	return &MockTorrentService_Resume_Call{Call: _e.mock.On("Resume", ctx, infoHash)}
}

func (_c *MockTorrentService_Resume_Call) Run(run func(ctx context.Context, infoHash string)) *MockTorrentService_Resume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTorrentService_Resume_Call) Return(err error) *MockTorrentService_Resume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTorrentService_Resume_Call) RunAndReturn(run func(ctx context.Context, infoHash string) error) *MockTorrentService_Resume_Call {
	_c.Call.Return(run)
	return _c
}
